import { db } from "./index";
import { listings, type NewListing } from "./schema";

const seedListings: NewListing[] = [
  {
    title: "Villa Sunset Paradise",
    description: "Magnifique villa en bord de mer avec vue panoramique sur la Méditerranée. Cette propriété de luxe dispose d'une piscine à débordement, d'un jardin tropical et d'une terrasse parfaite pour les couchers de soleil.",
    location: "Nice, Côte d'Azur",
    address: "15 Promenade des Anglais",
    city: "Nice",
    country: "France",
    latitude: "43.6957",
    longitude: "7.2714",
    bedrooms: 5,
    bathrooms: 4,
    maxGuests: 10,
    surface: 350,
    amenities: [
      "wifi",
      "pool",
      "air_conditioning",
      "kitchen",
      "parking",
      "sea_view",
      "jacuzzi",
      "garden",
      "terrace",
      "bbq",
    ],
    houseRules: {
      pets: false,
      smoking: false,
      parties: false,
      checkIn: "16:00",
      checkOut: "10:00",
    },
    images: [
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800",
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800",
    ],
    coverImage: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800",
    status: "published",
    featured: true,
  },
  {
    title: "Villa Azure Dream",
    description: "Villa moderne et spacieuse avec piscine chauffée, située dans un quartier calme. Parfaite pour des vacances en famille avec tous les conforts modernes et un grand jardin paysagé.",
    location: "Cannes, Côte d'Azur",
    address: "28 Boulevard de la Croisette",
    city: "Cannes",
    country: "France",
    latitude: "43.5511",
    longitude: "7.0128",
    bedrooms: 4,
    bathrooms: 3,
    maxGuests: 8,
    surface: 280,
    amenities: [
      "wifi",
      "pool",
      "air_conditioning",
      "kitchen",
      "parking",
      "garden",
      "terrace",
      "bbq",
      "gym",
    ],
    houseRules: {
      pets: true,
      smoking: false,
      parties: false,
      checkIn: "15:00",
      checkOut: "11:00",
    },
    images: [
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800",
      "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800",
    ],
    coverImage: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800",
    status: "published",
    featured: true,
  },
  {
    title: "Villa Méditerranée Charme",
    description: "Charmante villa traditionnelle avec une architecture provençale authentique. Située à proximité du centre-ville, elle offre un cadre paisible avec un magnifique olivier centenaire.",
    location: "Antibes, Côte d'Azur",
    address: "42 Chemin des Sables",
    city: "Antibes",
    country: "France",
    latitude: "43.5808",
    longitude: "7.1251",
    bedrooms: 3,
    bathrooms: 2,
    maxGuests: 6,
    surface: 180,
    amenities: [
      "wifi",
      "pool",
      "air_conditioning",
      "kitchen",
      "parking",
      "garden",
      "terrace",
    ],
    houseRules: {
      pets: false,
      smoking: false,
      parties: false,
      checkIn: "14:00",
      checkOut: "11:00",
    },
    images: [
      "https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4?w=800",
      "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800",
    ],
    coverImage: "https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4?w=800",
    status: "published",
    featured: false,
  },
  {
    title: "Villa Horizon Bleu",
    description: "Villa contemporaine avec design minimaliste et vue mer imprenable. Équipée des dernières technologies domotiques, piscine à débordement et home cinéma privé.",
    location: "Saint-Tropez, Côte d'Azur",
    address: "7 Route des Plages",
    city: "Saint-Tropez",
    country: "France",
    latitude: "43.2677",
    longitude: "6.6407",
    bedrooms: 6,
    bathrooms: 5,
    maxGuests: 12,
    surface: 450,
    amenities: [
      "wifi",
      "pool",
      "air_conditioning",
      "kitchen",
      "parking",
      "sea_view",
      "jacuzzi",
      "garden",
      "terrace",
      "bbq",
      "gym",
      "home_cinema",
    ],
    houseRules: {
      pets: false,
      smoking: false,
      parties: true,
      checkIn: "17:00",
      checkOut: "12:00",
    },
    images: [
      "https://images.unsplash.com/photo-1600585154084-4e5fe7c39198?w=800",
      "https://images.unsplash.com/photo-1600563438938-a9a27216b4f5?w=800",
      "https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?w=800",
      "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?w=800",
    ],
    coverImage: "https://images.unsplash.com/photo-1600585154084-4e5fe7c39198?w=800",
    status: "published",
    featured: true,
  },
  {
    title: "Villa Jardin Secret",
    description: "Villa intimiste entourée d'un jardin luxuriant avec fontaine et bassins. Idéale pour une escapade romantique ou des vacances en couple dans un cadre enchanteur.",
    location: "Menton, Côte d'Azur",
    address: "33 Avenue des Jardins",
    city: "Menton",
    country: "France",
    latitude: "43.7750",
    longitude: "7.4950",
    bedrooms: 2,
    bathrooms: 2,
    maxGuests: 4,
    surface: 120,
    amenities: [
      "wifi",
      "air_conditioning",
      "kitchen",
      "parking",
      "garden",
      "terrace",
      "bbq",
    ],
    houseRules: {
      pets: true,
      smoking: false,
      parties: false,
      checkIn: "15:00",
      checkOut: "11:00",
    },
    images: [
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800",
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800",
    ],
    coverImage: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800",
    status: "published",
    featured: false,
  },
  {
    title: "Villa Prestige Monaco",
    description: "Villa d'exception avec vue sur Monaco et la mer. Prestations haut de gamme, service de conciergerie disponible, cave à vin climatisée et parking pour 4 véhicules.",
    location: "Beausoleil, Monaco",
    address: "12 Avenue de Grande-Bretagne",
    city: "Beausoleil",
    country: "France",
    latitude: "43.7441",
    longitude: "7.4250",
    bedrooms: 7,
    bathrooms: 6,
    maxGuests: 14,
    surface: 550,
    amenities: [
      "wifi",
      "pool",
      "air_conditioning",
      "kitchen",
      "parking",
      "sea_view",
      "jacuzzi",
      "garden",
      "terrace",
      "bbq",
      "gym",
      "home_cinema",
      "sauna",
      "wine_cellar",
    ],
    houseRules: {
      pets: false,
      smoking: false,
      parties: true,
      checkIn: "16:00",
      checkOut: "12:00",
    },
    images: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800",
      "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800",
      "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800",
    ],
    coverImage: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800",
    status: "published",
    featured: true,
  },
  {
    title: "Villa Bohème Chic",
    description: "Villa au style bohème avec décoration artistique unique. Piscine naturelle écologique, potager bio et ambiance zen pour une reconnexion avec la nature.",
    location: "Valbonne, Côte d'Azur",
    address: "18 Chemin des Collines",
    city: "Valbonne",
    country: "France",
    latitude: "43.6416",
    longitude: "7.0078",
    bedrooms: 3,
    bathrooms: 2,
    maxGuests: 6,
    surface: 200,
    amenities: [
      "wifi",
      "pool",
      "air_conditioning",
      "kitchen",
      "parking",
      "garden",
      "terrace",
      "bbq",
    ],
    houseRules: {
      pets: true,
      smoking: false,
      parties: false,
      checkIn: "15:00",
      checkOut: "11:00",
    },
    images: [
      "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800",
      "https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?w=800",
    ],
    coverImage: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800",
    status: "draft",
    featured: false,
  },
  {
    title: "Villa Panorama 360",
    description: "Villa architecturale unique avec baies vitrées panoramiques offrant une vue à 360° sur les Alpes et la mer. Design contemporain primé et équipements ultra-modernes.",
    location: "Èze, Côte d'Azur",
    address: "5 Route de la Moyenne Corniche",
    city: "Èze",
    country: "France",
    latitude: "43.7271",
    longitude: "7.3614",
    bedrooms: 4,
    bathrooms: 4,
    maxGuests: 8,
    surface: 320,
    amenities: [
      "wifi",
      "pool",
      "air_conditioning",
      "kitchen",
      "parking",
      "sea_view",
      "mountain_view",
      "jacuzzi",
      "garden",
      "terrace",
      "gym",
    ],
    houseRules: {
      pets: false,
      smoking: false,
      parties: false,
      checkIn: "16:00",
      checkOut: "11:00",
    },
    images: [
      "https://images.unsplash.com/photo-1600563438938-a9a27216b4f5?w=800",
      "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?w=800",
    ],
    coverImage: "https://images.unsplash.com/photo-1600563438938-a9a27216b4f5?w=800",
    status: "published",
    featured: true,
  },
];

async function seed() {
  try {
    console.log("🌱 Starting database seeding...");

    // Insert listings
    console.log("📝 Inserting listings...");
    const insertedListings = await db.insert(listings).values(seedListings).returning();
    
    console.log(`✅ Successfully inserted ${insertedListings.length} listings`);
    console.log("\n📊 Seeded listings:");
    insertedListings.forEach((listing) => {
      console.log(`  - ${listing.title} (ID: ${listing.id}) - ${listing.status}`);
    });

    console.log("\n🎉 Database seeding completed successfully!");
  } catch (error) {
    console.error("❌ Error seeding database:", error);
    throw error;
  }
}

seed()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
